# Generated by Django 5.1.5 on 2025-02-05 00:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_driverid', models.IntegerField(blank=True, null=True)),
                ('t_vehicleid', models.IntegerField(blank=True, null=True)),
                ('t_locationid', models.IntegerField()),
                ('t_arrival_date_time', models.DateTimeField()),
                ('t_shareno', models.IntegerField(default=0)),
                ('t_isshareornot', models.BooleanField()),
                ('t_status', models.CharField(default='open', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TripUsers',
            fields=[
                ('tu_id', models.AutoField(primary_key=True, serialize=False)),
                ('passenger_number', models.IntegerField(default=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing_app.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('passenger', 'Passenger'), ('driver', 'Driver')], default='passenger', max_length=10)),
                ('was_driver', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('max_passengers', models.IntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='ride_sharing_app.driverprofile')),
            ],
        ),
    ]
