# Generated by Django 5.1.5 on 2025-02-02 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverprofile',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='car_model',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='license_plate',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='vehicle_type',
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=50)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('max_passengers', models.IntegerField()),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('driver', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ride_sharing_app.driverprofile')),
            ],
        ),
    ]
