# Generated by Django 5.1.5 on 2025-02-03 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_app', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='ride_sharing_app.driverprofile'),
        ),
    ]
