# Generated by Django 5.1.5 on 2025-02-03 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_app', '0005_trip_t_vehicleid_alter_trip_t_driverid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('d_id', models.AutoField(primary_key=True, serialize=False)),
                ('d_vehicleid', models.IntegerField(blank=True, null=True)),
                ('d_license', models.CharField(max_length=50)),
                ('d_userid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
