# Generated by Django 5.1.5 on 2025-02-03 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_app', '0006_driver'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Driver',
        ),
    ]
