# Generated by Django 5.1.5 on 2025-02-03 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride_sharing_app', '0006_remove_trip_t_tripusersid_trip_t_vehicleid_and_more'),
        ('ride_sharing_app', '0007_delete_driver'),
    ]

    operations = [
    ]
